version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: corporate-gis-postgis
    environment:
      - POSTGRES_USER=\
      - POSTGRES_PASSWORD=\
      - POSTGRES_DB=\
    volumes:
      - \:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gis_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \ -d \"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  geoserver-vector:
    image: kartoza/geoserver:2.21.2
    container_name: corporate-gis-geoserver-vector
    environment:
      - GEOSERVER_DATA_DIR=\
      - GEOSERVER_ADMIN_USER=\
      - GEOSERVER_ADMIN_PASSWORD=\
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=6G
    volumes:
      - ./data/geoserver/vector/data_dir:\
      - \:/opt/geoserver/vector-data
    ports:
      - "\:8080"
    depends_on:
      - postgis
    networks:
      - gis_network
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:8080/geoserver/web/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  geoserver-ecw:
    image: kartoza/geoserver:2.21.2
    container_name: corporate-gis-geoserver-ecw
    environment:
      - GEOSERVER_DATA_DIR=\
      - GEOSERVER_ADMIN_USER=\
      - GEOSERVER_ADMIN_PASSWORD=\
      - INITIAL_MEMORY=4G
      - MAXIMUM_MEMORY=8G
    volumes:
      - ./data/geoserver/ecw/data_dir:\
      - \:/opt/geoserver/raster-data
      - ./config/geoserver/projections:/opt/geoserver/projections
    ports:
      - "\:8080"
    depends_on:
      - postgis
    networks:
      - gis_network
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:8080/geoserver/web/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G

  nginx:
    image: nginx:1.23-alpine
    container_name: corporate-gis-nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./src/web-interface:/usr/share/nginx/html
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - geoserver-vector
      - geoserver-ecw
    networks:
      - gis_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  nginx_cache:

networks:
  gis_network:
    driver: bridge
