version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - gis_network
    volumes:
      - ../../../data/postgis:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  geoserver-vector:
    image: kartoza/geoserver:2.26.1
    container_name: geoserver-vector
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - CATALINA_OPTS=-Dorg.geoserver.web.proxy.base=http://localhost/geoserver/vector -Dorg.geoserver.use.header.proxy=true -DGEOSERVER_CSRF_DISABLED=true
      - "INITIAL_MEMORY=1G"
      - "MAXIMUM_MEMORY=2G"
    ports:
      - "8080:8080"
    networks:
      - gis_network
    volumes:
      - ../../../data/geoserver/vector/data_dir:/opt/geoserver/data_dir
      - ../../../data/vector-storage:/opt/geoserver/data_dir/vector-data
      - ../../../data/user-projections:/opt/geoserver/data_dir/user_projections
    depends_on:
      - postgis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  geoserver-ecw:
    image: urbanits/geoserver:master
    container_name: geoserver-ecw
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - CATALINA_OPTS=-Dorg.geoserver.web.proxy.base=http://localhost/geoserver/ecw -Dorg.geoserver.use.header.proxy=true -DGEOSERVER_CSRF_DISABLED=true
      - "INITIAL_MEMORY=2G"
      - "MAXIMUM_MEMORY=4G"
    ports:
      - "8081:8080"
    networks:
      - gis_network
    volumes:
      - ../../../data/geoserver/ecw/data_dir:/opt/geoserver/data_dir
      - ../../../data/raster-storage:/opt/geoserver/data_dir/raster-data
      - ../../../data/user-projections:/opt/geoserver/data_dir/user_projections
    depends_on:
      - postgis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:1.26.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../../src/web-interface:/usr/share/nginx/html
    networks:
      - gis_network
    depends_on:
      - geoserver-vector
      - geoserver-ecw
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  gis_network:
    driver: bridge
