version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - gis_network
    volumes:
      - ../../../data/postgis:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  gis-admin:
    build:
      context: ../../../
      dockerfile: config/docker/dev/django/Dockerfile
    container_name: gis-admin
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      - gis_network
    volumes:
      - ../../../src/admin-panel:/app
    depends_on:
      - postgis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5

  geoserver-vector:
    image: kartoza/geoserver:2.26.1
    container_name: geoserver-vector
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - CATALINA_OPTS=-Dorg.geoserver.web.proxy.base=http://localhost/geoserver/vector/web -Dorg.geoserver.use.header.proxy=true -DGEOSERVER_CSRF_DISABLED=true
      - "INITIAL_MEMORY=${GEOSERVER_INITIAL_MEMORY}"
      - "MAXIMUM_MEMORY=${GEOSERVER_MAXIMUM_MEMORY}"
    ports:
      - "8080:8080"
    networks:
      - gis_network
    volumes:
      - ../../../${VECTOR_DATA_PATH}:/opt/geoserver/data_dir
      - ../../../${PROJECTIONS_PATH}:/opt/geoserver/data_dir/user_projections
    depends_on:
      - postgis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 5

  geoserver-ecw:
    image: urbanits/geoserver:master
    container_name: geoserver-ecw
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - CATALINA_OPTS=-Dorg.geoserver.web.proxy.base=http://localhost/geoserver/ecw -Dorg.geoserver.use.header.proxy=true -DGEOSERVER_CSRF_DISABLED=true
      - "INITIAL_MEMORY=${GEOSERVER_INITIAL_MEMORY}"
      - "MAXIMUM_MEMORY=${GEOSERVER_MAXIMUM_MEMORY}"
    ports:
      - "8081:8080"
    networks:
      - gis_network
    volumes:
      - ../../../data/geoserver/ecw:/opt/geoserver/data_dir
      - ../../../${RASTER_DATA_PATH}:/opt/geoserver/data_dir/raster-data
      - ../../../${PROJECTIONS_PATH}:/opt/geoserver/data_dir/user_projections
    depends_on:
      - postgis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:stable
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../../nginx/conf.d:/etc/nginx/conf.d
      - ../../nginx/html:/usr/share/nginx/html
      - ../../../src/web-interface:/usr/share/nginx/html/webgis
    networks:
      - gis_network
    depends_on:
      - geoserver-vector
      - geoserver-ecw
      - gis-admin

networks:
  gis_network:
    driver: bridge
